version: '3.5'
services:
  db:
    image: mongo:7.0 #เปลี่ยนให้ตรงกับที่ใช้
    ports:
      - "27017:27017"
      
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=foodmood
      - DB_PORT=27017
    depends_on:
      - db

  frontend:
    build:
      context: ./FoodMood
      dockerfile: dockerfile.dev
    ports:
      - "80:80"
    depends_on:
      - backend

#version: "3.5"

#services:
#  backend:
#    build:
#      context: ./backend
#      dockerfile: dockerfile.dev

#  db:
#    image: mongo:7.0
#    ports:
#      - "26666:27017"

#  web:
#    build: 
#      context: ./FoodMood
#      dockerfile: dockerfile.dev
#    ports:
#      - "8080:3000"
  
#    command: ["sh", "-c", "sleep 5 && npm start"]


